# docker-compose.yml
version: "3.8"
services:
  database:
    image: postgres
    container_name: local_pgdb
    restart: always
    networks:
      - webnet
    env_file: ./database/.env
    volumes:
      - itakagreen-db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8081:8080
    volumes:
      - itakagreen-db:/var/lib/postgresql/data
    depends_on:
      - database
    networks:
      - webnet
      
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
      target: ${NODE_ENV}
    env_file: ./api/.env
    volumes:
      - ./api:/usr/src/app
    networks:
      - webnet
      - app-network
    ports:
      - "8080:8080"
    depends_on:
      - database
      
  front:
    container_name: front
    build:
      context: ./front
      dockerfile: Dockerfile
      target: ${NODE_ENV}
    env_file: ./front/.env
    ports:
      - 3000:3000
    volumes:
      - ./front:/opt/app
    networks:
      - app-network

networks:
  webnet:
  app-network:
volumes:
  itakagreen-db:
