# docker-compose.yml
version: "3.8"
services:
  database:
    image: postgres
    container_name: local_pgdb
    restart: always
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./database/local_pgdatabase:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "6081:80"
    networks:
      - webnet
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
      target: ${NODE_ENV}
    command: npm run start:dev
    env_file: ./api/.env
    volumes:
      - ./api:/usr/src/app
      - ./api/node_modules:/usr/src/app/node_modules
    networks:
      - webnet
      - app-network
    ports:
      - "8080:8080"
    depends_on:
      - database
  
  front-dev:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    command: npm run dev
    ports:
      - 3000:3000
    volumes:
      - ./front:/opt/app
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  front-prod:
    container_name: nextjs-prod
    build:
      target: production
      context: ./front
      dockerfile: Dockerfile.prod
    restart: on-failure
    volumes:
      - ./front:/opt/app
      - /opt/app/node_modules
      - /opt/app/.next
    ports:
      - '8000:8000'
    networks:
      - app-network

  #   api:
  # hostname: api
  # build:
  #   context: ./api
  #   dockerfile: Dockerfile
  #   target: development
  # command: npm run start:dev
  # env_file: ./api/.env
  # restart: always
  # volumes:
  #   - ./api:/usr/src/api
  #   - ./api/node_modules:/usr/src/api/node_modules
  # networks:
  #   - webnet
  # ports:
  #   - 8080:8080
  # depends_on:
  #   - database


networks:
  webnet:
  app-network:
volumes:
  pgadmin-data: