import '../styles/globals.css'
import Head from 'next/head'
import type { AppProps } from 'next/app'
import Layouts from '../components/layouts'

export default function App({ Component, pageProps }: AppProps) {

  return (
    <>
      <Head>
        <title>ItakaGreen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://kit.fontawesome.com/23d341672d.js" crossOrigin="anonymous" />
      </Head>
      <Layouts>
           <Component {...pageProps} />
      </Layouts>
    </>
  )
}


